"""init

Revision ID: 32180eda02c4
Revises: 2b8cf9f9a902
Create Date: 2022-05-08 18:52:06.369085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32180eda02c4'
down_revision = '2b8cf9f9a902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
