"""init

Revision ID: 57173c56f8da
Revises: d59b9044f7eb
Create Date: 2022-05-07 12:28:49.309349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57173c56f8da'
down_revision = 'd59b9044f7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'name')
    # ### end Alembic commands ###
