"""init

Revision ID: a97e32463b11
Revises: 57e2226ff3ea
Create Date: 2022-05-07 11:52:48.715276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97e32463b11'
down_revision = '57e2226ff3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed')
    # ### end Alembic commands ###
